### ISSUE TITLE
Rclone erroring with SSL certificate

### ISSUE THREAD

**Issue by handshake87** [marcone/teslausb#481] opened 2020-05-06 00:19 UTC
Following you guide advises to use curl to install rclone. While following these steps it actually never install with an error stating SSL certificate is missing. Any solution for this? Maybe add this step in the rclone guide

**Comment by marcone** [comment] 2020-05-06 00:29
What's the actual error you're seeing?

**Comment by handshake87** [comment] 2020-05-06 02:33
I get the following error message:

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

**Comment by marcone** [comment] 2020-05-06 02:59
and what command are you running to get that error?

When I run `curl https://rclone.org/install.sh | sudo bash`, which is the command listed on [teslausb's rclone setup page](https://github.com/marcone/teslausb/blob/main-dev/doc/SetupRClone.md), and is a direct copy from the [rclone website](https://rclone.org/downloads/), it works just fine.

**Comment by thijsdejong** [comment] 2020-05-06 15:34
I actually got this same error when trying to install a freshly generated image. It was unable to because of that exact ssl error message.

**Comment by marcone** [comment] 2020-05-06 16:03
By "freshly generated" do you mean you built your own image?

**Comment by marcone** [comment] 2020-05-06 17:13
Also, is it only the curl for rclone that fails, or does teslausb itself fail to install? (since that also uses curl pull the scripts from github)

**Comment by handshake87** [comment] 2020-05-06 17:14
Only the rcurl command. While trying to grab it we get a SSL error.

**Comment by thijsdejong** [comment] 2020-05-07 12:41
> By "freshly generated" do you mean you built your own image?

Yes I built my own image. It's curl that fails in general, so headless install fails aswell. Thinking it might be related.

**Comment by sebnaf** [comment] 2020-05-14 21:04
Please check your system date/time. In my case the Pi was way off and all SSL certs failed validation (yes, still ntpd issues…)

**Comment by marcone** [comment] 2020-08-12 03:26
Closing because this issue over 3 months old, and I can't reproduce it

**Closed as completed by marcone** 2020-08-12 03:26 UTC
