### ISSUE TITLE
2023 Model Y Does Not See Drive

### ISSUE THREAD

**Issue by Snow-Okami** [marcone/teslausb#752] opened 2023-01-05 09:22 UTC
### Describe the problem

I just got a Model Y and have been trying to get this to work with no success. 3 years ago, I had this working beautifully on my 2020 Model 3 with no issues. I moved and waited a bit to redo it and it seems to not work on the latest software with either car. It sometimes works on the 3 but I haven't figured out why it does only sometimes.

It is formatted with a Music drive and a Cam drive. I can hook the pi up to a computer and both partitions are working and can be interacted with. If I drop video files in the cam drive and hook it up to only power, it will upload those files to my NAS without issue.

I also have a Pi Sugar 2 battery connected to the board, not sure if that could effect anything.

I have 2022.44.30.1 installed on the Y, 2022.44.25.5 on the 3.

### Device

Raspberry Pi Zero W

### OS Image

Prebuilt TeslaUSB image

### Car Model

Model Y

### USB connection

Glove box

**Comment by jhtx2023** [comment] 2023-01-07 20:50
I just installed on 2023 Model Y and everything seems to be working. I initially used a power only cable when I put the pi into the glovebox but once I figured out I had the wrong cable things started working.

now I am starting to explore adding bluetooth pan connection from the rpi to my mobile and then provide the tesla with network via the rpi wifi when I leave the garage,

**Comment by marcone** [comment] 2023-01-07 21:41
@Snow-Okami are you using the same cable when you connect to the computer vs. when you connect to the car? If it works with a computer then as far as TeslaUSB is concerned everything is working correctly.

**Comment by Snow-Okami** [comment] 2023-01-11 09:14
@marcone I am using the same cable. I have tried it on 3 separate computers and have switched the cable out to two different types. They are data cables. The only thing it doesn't work in, is the Tesla.

I do notice when I hook it up to the computer it doesn't instantly detect it at first, it shows a 'Setting up COM5 (Serial Device) in the bottom right hand corner, which after setup is complete, it then mounts the drives. It is also labeled as a 'TeslaUSB Composite Gadget'. It seems to mount instantly after that.

I reinstalled the latest image as well. I tried it also on my Model 3 with the same issue. Normal USB drives work fine. Perhaps it has something to do with FAT32? I did not try the reinstall with the exFAT option due to the TRIM disclaimer, but I noticed the drive that came with my Model Y was formatted as exFAT.

**Comment by marcone** [comment] 2023-01-11 18:08
FAT32 should work just as well. Does the car offer an option to format the drive?

**Comment by Snow-Okami** [comment] 2023-01-14 13:26
No, it gives no option. It doesn't detect the music drive either. I am thinking the partitioning of the drive may be confusing it. I will try to reinstall without the music drive and see if that solves it.

Thanks for all the support, I really appreciate it.

**Comment by marcone** [comment] 2023-01-14 19:37
Whether or not you configured a music drive shouldn't matter. It kind of sounds like you're using the wrong USB port on the Pi when you put it in the car. Note that on the Raspberry Pi Zero W the two USB ports are not the same, and you need to use the "USB" port to connect to the car, not the "PWR" port:
![59162752-5749b600-8aab-11e9-96e9-1b9f9e860bd0](https://user-images.githubusercontent.com/48169102/212492990-9c07ece7-ed6e-4356-886b-aab4e0c8c123.png)

**Comment by tribhuvanji** [comment] 2023-02-04 06:33
@Snow-Okami wondering if you got this working on your Y. On my 2022 MYP I needed to replace the USB module in the center console to get it working. At the time Tesla was shipping cars without the data chips in the USB module, the fix was to replace the module with a fully functional one (that utilizes the data cable that is routed to the console).

**Comment by droideggs** [comment] 2023-03-15 23:47
I'm also having a problem on the Model Y 2023. I am using a Raspberry Pi Zero W 2. Installation went smoothly, but when plugging in the pi to the usb-a glovebox port, it is not detecting it as a USB. I am using the startech micro USB to USB-A cable, and connected to the innermost micro USB port. Any reason why its not working? All other functions are working such as dashcam footage being properly sent to my MacOS.

**Comment by marcone** [comment] 2023-03-15 23:52
Where does this dashcam footage come from, if the car doesn't see the drive?
If you connect the Pi to a PC using the same cable, does the PC see the "CAM" drive?

**Comment by droideggs** [comment] 2023-03-16 00:07
the car is able to communicate with the pi, but i don't get the USB drive option under 'sources.' 
yes, when I connect the pi to the pc using the same cable, the PC recognizes the Pi. 
I get the 'rei-inerset usb into glovebox for higher speed' error. 
essentially everything works except that the car doesn't recognize it as a USB. i would have thought there would be a USB option under sources for the music but there isn't one


EDIT: its somehow working now. i reran the setup and now its somehow working? 

ran the following commands

manually deleted all bin (cam_disk, music_disk) files and shapshot folder in /backingfiles
ran /root/bin/setup-teslausb
manually mounted both /mnt/archive and /mnt/musicarchive (the installation somehow failed to mount the network shares for some reason) 
mount /mnt/archive
mount /mnt/musicarchive
rebooted

its now able to detect it as a usb and dashcam transferring is working as intended.

**Comment by marcone** [comment] 2023-03-16 00:45
> manually mounted both /mnt/archive and /mnt/musicarchive (the installation somehow failed to mount the network shares for some reason)

These are mounted and unmounted automatically by TeslaUSB as needed for the duration of archiving/syncing. You do not need to mount them manually, and the car doesn't see these anyway.

**Closed as completed** 2024-04-08 01:16 UTC
