### ISSUE TITLE
USB Device Not Fast Enough

### ISSUE THREAD

**Issue by DonC52** [marcone/teslausb#218] opened 2019-09-03 03:48 UTC
I get the message from my Tesla saying that my USB device is not fast enough. It does not happen all the time but I have only had this running for a couple of days.

**Comment by marcone** [comment] 2019-09-03 03:54
Duplicate of https://github.com/marcone/teslausb/issues/217

**Closed as completed by marcone** 2019-09-03 03:54 UTC

**Comment by DonC52** [comment] 2019-09-03 03:56
I got a fast SanDisk 64GB Ultra Class 10 card. Its a camera card that full HD Video can be recorded on.
