### ISSUE TITLE
Saving RecentClips

### ISSUE THREAD

**Issue by deece** [marcone/teslausb#604] opened 2021-01-26 07:22 UTC
I'd like to archive whatever is available from RecentClips too.

Are there any objections to patches that would (optionally) enable this functionality?

Can you explain the rationale for omitting this?

Thanks

**Comment by marcone** [comment] 2021-01-26 07:30
Duplicate of https://github.com/marcone/teslausb/issues/114

**Closed as completed by marcone** 2021-01-26 07:30 UTC
