### ISSUE TITLE
Raspberry Pi 4 coil whine

### ISSUE THREAD

**Issue by edwardrossi** [marcone/teslausb#685] opened 2021-10-03 09:46 UTC
Hi all,

This topic was surfaced in the discord but I wanted to get a larger sample size.

Is anyone else observing fairly loud coil whine on the Pi 4 and if so, what did your troubleshooting find? 

I'm wondering whether it a QA issue with my Pi and a new one will remedy this?
I have a 2021 M3 MIC SR+, Pi 4 (4gb ram) in an armour passive heatsink case plugged into the glove box USB port.
I'm currently booting from the 128gb Tesla USB, but the whine persisted when booting from SD card as well.
 
It has been noted that perhaps the Tesla is providing 'dirty' power to be the cause of the whine but it would appear, at least on the surface that this is only affecting a very small portion of users as not much has been said on this topic.

**Comment by roflmao** [comment] 2021-10-08 07:30
I can confirm this, 2021 M3MIC SR+, Pi4 4gbram in the glovebox.

**Comment by edwardrossi** [comment] 2021-10-08 11:55
I don't know if it's a global supply issue or just an Australian supply issue but it's impossible to buy a pi4 in Australia right now. I want to test with a 2gb model (as I will need the 4gb for another project anyway) but no one is expecting stock until early 2022...

Edit #1:
I spoke too soon. The only electronics retail chain in Australia was sold out at all locations except for a small industrial outer suburb. By the looks of it, I just bought the last 2gb model in the state, perhaps even the country.

I'll report back tomorrow confirming whether is a QA issue with the RPi4, a specific issue with variants above 2gb or whether it's simply a Tesla USB voltage supply issue.

Edit #2: I once again spoke too soon. I got a call this morning saying that they looked everywhere and couldn't find a 2gb rpi in stock, nor could they find one in inventory at any of their other stores... 

The search continues.

**Comment by roflmao** [comment] 2021-10-11 18:44
@edwardrossi i put in in the center console through a usb hub, no whine.

**Comment by edwardrossi** [comment] 2021-10-25 03:52
@roflmao I plugged mine into the centre console as well through a USB hub and the whine persisted. I assume your USB hub might have a capacitor inline somewhere to smooth out the voltage.

I ended up buying another RPi (I could only source a 4GB) to test and this also didn't yield any different results.

My next step will be to place a capacitor inline on a USB cable, and test if that smooths out the supply. If so, I'll 3D print some sort of adapter to place between the USB port and the RPi. 

Out of curiosity, I raise this issue to Tesla Service. They said the following: 

1. (understandably), they first said RPi's aren't supported devices so there's not much they could do except check the wire harness for loose connectors.
2. This is the first they're hearing about a "dirty" power supply coming from the USB ports.
3. Until recently, MIC M3's used different components for glovebox USB than Fremont builds. Fremont builds now uses the same components.
4. There has been previous reports of third party wireless charges emitting noise, interfering with FM radio signals.
5. He has flagged the issue with Tesla engineers and will let me know if anything eventuates from it.

**Comment by edwardrossi** [comment] 2021-10-30 02:34
After reading through #564 again, It appears the voltage coming out the glovebox USB is not 5V but 5.2V. I wonder if some usb hubs (like the one you're using) are regulating the input voltage to the USB standard of 5V?

@roflmao would you be able to test the USB hub in the Glovebox using a USB 3.0/3.1 Type-A to Type-C adapter?

**Comment by marcone** [comment] 2021-10-30 02:44
> After reading through #564 again, It appears the voltage coming out the glovebox USB is not 5V but 5.2V. I wonder if some usb hubs (like the one you're using) are regulating the input voltage to the USB standard of 5V?

USB allows up to 5.25V, so 5.2V is still within spec.

**Comment by CodeChief** [comment] 2021-11-01 23:45
> > After reading through #564 again, It appears the voltage coming out the glovebox USB is not 5V but 5.2V. I wonder if some usb hubs (like the one you're using) are regulating the input voltage to the USB standard of 5V?
> 
> USB allows up to 5.25V, so 5.2V is still within spec.

![image](https://user-images.githubusercontent.com/1496225/139756611-797c61d1-8d56-43a9-8c08-1b76e3150fbb.png)

Actually I measured 5.48v with a RasPi 4.

**Comment by roflmao** [comment] 2021-11-02 19:57
@edwardrossi I dont have one at the time being, but will try to get a hold of one.

**Comment by CodeChief** [comment] 2021-11-03 00:45
According to my son who's an electronics master this is most likely caused by impedance mismatch. This is difficult to correct on the "load side" as you have to know the impedance of the PCB design.

You can't just whack resistors on there as the device already has resistors according to USB specification for identification and speed select.

From what I understand, I think we have the same general problem here as with the other USB adapter/glovebox issues. Although it sounds like a Tesla design problem (for example if their PCB traces/resistors don't amount to the impedance of USB specifications or are living on the edge of them), it might still be a RasPi configuration/hardware problem. 

How does the RasPi identify itself correctly when switching behaviour from a USB host to USB gadget? Does it really appear as a USB storage device with the correct impedance for USB 3.x or is this just a leftover Linux Kernel hack and we are lucky it works at all as it's really out of spec, not the car?

The Pi is really a special device with this capability, like a Smartphone, so we should not assume it's Tesla's fault and first look at any issues (and potential hackable fixes) on the Pi. I am not a hardware engineer so all I can do is hope that points some others in the right direction.

I guess a sensible test to rule out configuration would be to connect a RasPi without the gadget driver. Just a completely plain image, perhaps also load the EEPROM recovery image first to make sure it's factory default. Then repeat the same test with the USB gadget mode enabled, but only that as [originally documented](https://www.reddit.com/r/teslamotors/comments/9m9gyk/build_a_smart_usb_drive_for_your_tesla_dash_cam/) , on its own, not the whole TeslaUSB image.

**Comment by marcone** [comment] 2021-11-23 01:28
Closing this since it's not a teslausb issue

**Closed as completed by marcone** 2021-11-23 01:28 UTC
